# app/analytics/report.py
# ============================================================
# ACADEMIC REPORT GENERATOR
#
# Produces a PDF that looks like a university skills evaluation
# report. Uses ReportLab — a pure-Python PDF library that needs
# no external dependencies beyond pip install reportlab.
#
# The report is structured like a professor's evaluation form:
#   1. Header (student + role + date)
#   2. Executive summary (readiness score + interpretation)
#   3. Skills inventory table (known vs required)
#   4. Competency gap analysis
#   5. Recommended learning roadmap
#   6. Semester study plan table
#   7. Score breakdown section
#
# All content is generated deterministically from the analysis
# functions — no randomness, no ML. A professor can verify every
# number in the report by running the same functions manually.
# ============================================================

import io
from datetime import date

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, KeepTogether,
)
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT

from app.analytics.readiness import calculate_readiness
from app.analytics.planner import generate_study_plan
from app.graph_engine import compute_skill_gap


# ── Brand colors (matches frontend CSS variables) ────────────
COLOR_KNOWN   = colors.HexColor("#16a34a")   # green
COLOR_MISSING = colors.HexColor("#dc2626")   # red
COLOR_ACCENT  = colors.HexColor("#18181b")   # near-black
COLOR_MUTED   = colors.HexColor("#71717a")   # grey
COLOR_BG_LIGHT= colors.HexColor("#f7f7f5")   # warm off-white
COLOR_BORDER  = colors.HexColor("#e4e3de")   # light border
COLOR_NEXT    = colors.HexColor("#d97706")   # amber


def generate_report_pdf(
    user_skills: list[str],
    target_role: str,
    student_name: str = "Student",
    hours_per_week: int = 6,
    months: int = 3,
) -> bytes:
    """
    Generate a complete academic PDF report for a student's career readiness.

    All analytical computations (readiness score, gap analysis, study plan)
    are performed fresh inside this function. The PDF is assembled from those
    results using ReportLab's platypus document layout engine.

    Args:
        user_skills:    Canonical skill names the student has.
        target_role:    Career role key (from TARGET_ROLES).
        student_name:   Name shown in the report header.
        hours_per_week: Weekly study capacity (for study plan).
        months:         Total months for the study plan.

    Returns:
        bytes: Raw PDF file content, suitable for returning as a
               FastAPI StreamingResponse or saving to disk.

    Academic use:
        A professor can trigger this endpoint for each student,
        collect PDFs, and use them as standardized evaluation artifacts
        in a portfolio assessment or advising session.
    """
    # ── Run all analyses ──────────────────────────────────────────
    readiness = calculate_readiness(user_skills, target_role)
    gap       = compute_skill_gap(user_skills, target_role)
    plan      = generate_study_plan(user_skills, target_role, hours_per_week, months)

    # ── Setup PDF document ────────────────────────────────────────
    buffer = io.BytesIO()
    doc    = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=2.2 * cm,
        leftMargin=2.2 * cm,
        topMargin=2.0 * cm,
        bottomMargin=2.0 * cm,
        title=f"Career Readiness Report — {student_name}",
        author="Career Architect System",
    )

    styles = _build_styles()
    story  = []

    # ══════════════════════════════════════════════════════════════
    # SECTION 0: Header
    # ══════════════════════════════════════════════════════════════
    story.append(Paragraph("CAREER ARCHITECT", styles["eyebrow"]))
    story.append(Spacer(1, 0.15 * cm))
    story.append(Paragraph("Career Readiness Evaluation Report", styles["h1"]))
    story.append(Spacer(1, 0.4 * cm))

    # Metadata table (student name, role, date)
    meta_data = [
        ["Student",      student_name],
        ["Target Role",  target_role],
        ["Report Date",  date.today().strftime("%d %B %Y")],
        ["Generated by", "Career Architect v0.1 — Knowledge Graph Engine"],
    ]
    meta_table = Table(meta_data, colWidths=[4 * cm, 12 * cm])
    meta_table.setStyle(TableStyle([
        ("FONTNAME",    (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME",    (1, 0), (1, -1), "Helvetica"),
        ("FONTSIZE",    (0, 0), (-1, -1), 9),
        ("TEXTCOLOR",   (0, 0), (0, -1), COLOR_MUTED),
        ("TEXTCOLOR",   (1, 0), (1, -1), COLOR_ACCENT),
        ("TOPPADDING",  (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING",(0,0), (-1, -1), 3),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 0.5 * cm))
    story.append(HRFlowable(width="100%", thickness=1.5, color=COLOR_ACCENT))
    story.append(Spacer(1, 0.5 * cm))

    # ══════════════════════════════════════════════════════════════
    # SECTION 1: Executive Summary
    # ══════════════════════════════════════════════════════════════
    story.append(Paragraph("1. Executive Summary", styles["h2"]))
    story.append(Spacer(1, 0.2 * cm))

    # Score display
    score_color = _score_color(readiness["score"])
    summary_data = [
        ["Readiness Score", f"{readiness['score']} / 100"],
        ["Coverage Score (60 pts max)", f"{readiness['component_coverage']:.1f}"],
        ["Proximity Score (40 pts max)", f"{readiness['component_proximity']:.1f}"],
        ["Estimated Difficulty", readiness["estimated_difficulty"]],
        ["Skills Held (required)", f"{readiness['known_skills_count']} of {readiness['total_required']}"],
        ["Skills Missing", str(readiness["missing_skills_count"])],
        ["Avg. Graph Distance to Gaps", f"{readiness['avg_graph_distance']:.1f} hops"],
    ]
    summary_table = Table(summary_data, colWidths=[8 * cm, 8 * cm])
    summary_table.setStyle(TableStyle([
        ("BACKGROUND",  (0, 0), (-1, 0), COLOR_ACCENT),
        ("TEXTCOLOR",   (0, 0), (-1, 0), colors.white),
        ("FONTNAME",    (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTNAME",    (0, 1), (0, -1), "Helvetica-Bold"),
        ("FONTNAME",    (1, 1), (1, -1), "Helvetica"),
        ("FONTSIZE",    (0, 0), (-1, -1), 9.5),
        ("TEXTCOLOR",   (0, 1), (0, -1), COLOR_MUTED),
        ("TEXTCOLOR",   (1, 1), (1, -1), COLOR_ACCENT),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [None, COLOR_BG_LIGHT]),
        ("GRID",        (0, 0), (-1, -1), 0.5, COLOR_BORDER),
        ("TOPPADDING",  (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING",(0,0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(summary_table)
    story.append(Spacer(1, 0.3 * cm))
    story.append(Paragraph(
        f"<i>{readiness['interpretation']}</i>",
        styles["interpretation"]
    ))
    story.append(Spacer(1, 0.6 * cm))

    # ══════════════════════════════════════════════════════════════
    # SECTION 2: Skills Inventory
    # ══════════════════════════════════════════════════════════════
    story.append(Paragraph("2. Skills Inventory", styles["h2"]))
    story.append(Spacer(1, 0.15 * cm))
    story.append(Paragraph(
        "The table below lists all skills required for the target role, "
        "classified by the student's current status.",
        styles["body"]
    ))
    story.append(Spacer(1, 0.25 * cm))

    inv_header = [["Skill", "Status", "Domain"]]
    inv_rows   = []

    # Collect all required skills, mark known vs missing
    from app.graph_engine import TARGET_ROLES, SKILL_DOMAINS
    required = TARGET_ROLES.get(target_role, [])

    known_set   = set(gap["known_skills"])
    for skill in sorted(required):
        status = "✓ Known" if skill in known_set else "✗ Missing"
        domain = SKILL_DOMAINS.get(skill, "—").capitalize()
        inv_rows.append([skill, status, domain])

    inv_data = inv_header + inv_rows
    inv_table = Table(inv_data, colWidths=[7 * cm, 4 * cm, 5 * cm])
    inv_style = [
        ("BACKGROUND",   (0, 0), (-1, 0), COLOR_ACCENT),
        ("TEXTCOLOR",    (0, 0), (-1, 0), colors.white),
        ("FONTNAME",     (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTNAME",     (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE",     (0, 0), (-1, -1), 9),
        ("GRID",         (0, 0), (-1, -1), 0.5, COLOR_BORDER),
        ("ROWBACKGROUNDS",(0, 1), (-1, -1), [colors.white, COLOR_BG_LIGHT]),
        ("TOPPADDING",   (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING",(0, 0), (-1, -1), 5),
        ("LEFTPADDING",  (0, 0), (-1, -1), 8),
    ]
    # Color-code status column
    for i, row in enumerate(inv_rows, start=1):
        if "Known" in row[1]:
            inv_style.append(("TEXTCOLOR", (1, i), (1, i), COLOR_KNOWN))
            inv_style.append(("FONTNAME",  (1, i), (1, i), "Helvetica-Bold"))
        else:
            inv_style.append(("TEXTCOLOR", (1, i), (1, i), COLOR_MISSING))
    inv_table.setStyle(TableStyle(inv_style))
    story.append(inv_table)
    story.append(Spacer(1, 0.6 * cm))

    # ══════════════════════════════════════════════════════════════
    # SECTION 3: Competency Gap Analysis
    # ══════════════════════════════════════════════════════════════
    story.append(Paragraph("3. Competency Gap Analysis", styles["h2"]))
    story.append(Spacer(1, 0.15 * cm))

    if not gap["missing_skills"]:
        story.append(Paragraph(
            "No competency gaps identified. The student meets all requirements for this role.",
            styles["body"]
        ))
    else:
        story.append(Paragraph(
            "The following required competencies are not yet present in the student's profile. "
            "Each row shows the shortest prerequisite path from the student's existing knowledge "
            "to the missing skill (graph shortest-path algorithm).",
            styles["body"]
        ))
        story.append(Spacer(1, 0.25 * cm))

        gap_header = [["Missing Skill", "Shortest Learning Path"]]
        gap_rows   = []
        for skill in sorted(gap["missing_skills"]):
            path = gap["learning_paths"].get(skill, [skill])
            path_str = " → ".join(path)
            gap_rows.append([skill, path_str])

        gap_data  = gap_header + gap_rows
        gap_table = Table(gap_data, colWidths=[5 * cm, 11 * cm])
        gap_style = [
            ("BACKGROUND",   (0, 0), (-1, 0), COLOR_MISSING),
            ("TEXTCOLOR",    (0, 0), (-1, 0), colors.white),
            ("FONTNAME",     (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTNAME",     (0, 1), (-1, -1), "Helvetica"),
            ("FONTSIZE",     (0, 0), (-1, -1), 8.5),
            ("GRID",         (0, 0), (-1, -1), 0.5, COLOR_BORDER),
            ("ROWBACKGROUNDS",(0,1), (-1, -1), [colors.white, COLOR_BG_LIGHT]),
            ("TOPPADDING",   (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING",(0, 0), (-1, -1), 5),
            ("LEFTPADDING",  (0, 0), (-1, -1), 8),
            ("FONTNAME",     (0, 1), (0, -1), "Helvetica-Bold"),
            ("TEXTCOLOR",    (0, 1), (0, -1), COLOR_MISSING),
        ]
        gap_table.setStyle(TableStyle(gap_style))
        story.append(gap_table)
    story.append(Spacer(1, 0.6 * cm))

    # ══════════════════════════════════════════════════════════════
    # SECTION 4: Recommended Learning Roadmap
    # ══════════════════════════════════════════════════════════════
    story.append(Paragraph("4. Recommended Learning Roadmap", styles["h2"]))
    story.append(Spacer(1, 0.15 * cm))
    story.append(Paragraph(
        "The following ordered sequence represents the prerequisite-respecting learning path "
        "from the student's current knowledge base to full role readiness. "
        "Skills are ordered so each skill's prerequisites appear before it.",
        styles["body"]
    ))
    story.append(Spacer(1, 0.25 * cm))

    if plan["skills_to_learn"]:
        for i, skill in enumerate(plan["skills_to_learn"], 1):
            story.append(Paragraph(
                f"<b>{i}.</b> {skill}",
                styles["roadmap_item"]
            ))
        story.append(Spacer(1, 0.6 * cm))
    else:
        story.append(Paragraph("No additional skills required.", styles["body"]))
        story.append(Spacer(1, 0.6 * cm))

    # ══════════════════════════════════════════════════════════════
    # SECTION 5: Study Plan
    # ══════════════════════════════════════════════════════════════
    story.append(Paragraph("5. Semester Study Plan", styles["h2"]))
    story.append(Spacer(1, 0.15 * cm))
    story.append(Paragraph(plan["summary"], styles["body"]))
    story.append(Spacer(1, 0.25 * cm))

    if plan["weeks"]:
        plan_header = [["Week", "Skill", "Intensity", "Est. Hours", "Study Tip"]]
        plan_rows   = []
        for block in plan["weeks"]:
            wk = (f"{block['week_start']}" if block["week_start"] == block["week_end"]
                  else f"{block['week_start']}–{block['week_end']}")
            plan_rows.append([
                wk,
                block["skill"],
                block["difficulty"],
                str(block["hours_required"]),
                block["study_tips"],
            ])

        plan_data  = plan_header + plan_rows
        plan_table = Table(
            plan_data,
            colWidths=[1.5 * cm, 4.5 * cm, 2.0 * cm, 1.8 * cm, 6.2 * cm]
        )
        plan_style = [
            ("BACKGROUND",   (0, 0), (-1, 0), COLOR_NEXT),
            ("TEXTCOLOR",    (0, 0), (-1, 0), colors.white),
            ("FONTNAME",     (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTNAME",     (0, 1), (-1, -1), "Helvetica"),
            ("FONTSIZE",     (0, 0), (-1, -1), 7.5),
            ("GRID",         (0, 0), (-1, -1), 0.5, COLOR_BORDER),
            ("ROWBACKGROUNDS",(0,1), (-1, -1), [colors.white, COLOR_BG_LIGHT]),
            ("TOPPADDING",   (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING",(0, 0), (-1, -1), 4),
            ("LEFTPADDING",  (0, 0), (-1, -1), 5),
            ("VALIGN",       (0, 0), (-1, -1), "TOP"),
        ]
        plan_table.setStyle(TableStyle(plan_style))
        story.append(plan_table)
    else:
        story.append(Paragraph("No study plan needed — student is already qualified.", styles["body"]))

    story.append(Spacer(1, 0.8 * cm))

    # ══════════════════════════════════════════════════════════════
    # SECTION 6: Score Methodology
    # ══════════════════════════════════════════════════════════════
    story.append(HRFlowable(width="100%", thickness=0.5, color=COLOR_BORDER))
    story.append(Spacer(1, 0.3 * cm))
    story.append(Paragraph("6. Score Methodology", styles["h2"]))
    story.append(Spacer(1, 0.15 * cm))
    methodology_text = (
        "<b>Coverage Component (0–60 points):</b> "
        "Fraction of role-required skills already present in the student's profile, "
        "multiplied by 60. Formula: (known_count / total_required) × 60.<br/><br/>"
        "<b>Proximity Component (0–40 points):</b> "
        "Average shortest directed path (graph hops) from the student's skills to each "
        "missing required skill, normalized against a maximum distance of 8 hops. "
        "Formula: (1 − avg_distance / 8) × 40.<br/><br/>"
        "<b>Difficulty Classification:</b> "
        "Low (&lt;2 avg hops), Medium (2–4 hops), High (&gt;4 hops). "
        "Reflects how many prerequisite steps separate the student from their gaps.<br/><br/>"
        "<b>Graph Engine:</b> NetworkX DiGraph with 32 nodes, 41 manually curated edges. "
        "All paths computed using Dijkstra's BFS shortest-path algorithm (deterministic)."
    )
    story.append(Paragraph(methodology_text, styles["methodology"]))

    # ── Footer note ───────────────────────────────────────────────
    story.append(Spacer(1, 0.5 * cm))
    story.append(Paragraph(
        f"Generated by Career Architect Research System · {date.today().isoformat()} · "
        "All scores are fully reproducible and audit-able.",
        styles["footer"]
    ))

    # ── Build PDF ─────────────────────────────────────────────────
    doc.build(story)
    buffer.seek(0)
    return buffer.read()


def _score_color(score: int) -> colors.Color:
    """Map a score to a traffic-light color for visual emphasis."""
    if score >= 70:
        return COLOR_KNOWN    # green
    if score >= 40:
        return COLOR_NEXT     # amber
    return COLOR_MISSING      # red


def _build_styles() -> dict:
    """
    Build and return all paragraph styles used in the report.
    Centralising styles here makes it easy to reskin the report.
    """
    base   = getSampleStyleSheet()
    styles = {}

    styles["eyebrow"] = ParagraphStyle(
        "eyebrow",
        fontName="Helvetica-Bold", fontSize=8,
        textColor=COLOR_MUTED, spaceAfter=2,
        letterSpacing=1.5,
    )
    styles["h1"] = ParagraphStyle(
        "h1",
        fontName="Helvetica-Bold", fontSize=20,
        textColor=COLOR_ACCENT, spaceAfter=4,
        leading=24,
    )
    styles["h2"] = ParagraphStyle(
        "h2",
        fontName="Helvetica-Bold", fontSize=12,
        textColor=COLOR_ACCENT, spaceBefore=8, spaceAfter=4,
        borderPad=2,
    )
    styles["body"] = ParagraphStyle(
        "body",
        fontName="Helvetica", fontSize=9,
        textColor=COLOR_ACCENT, leading=14,
        spaceAfter=4,
    )
    styles["interpretation"] = ParagraphStyle(
        "interpretation",
        fontName="Helvetica-Oblique", fontSize=9,
        textColor=COLOR_MUTED, leading=13,
        leftIndent=10,
    )
    styles["roadmap_item"] = ParagraphStyle(
        "roadmap_item",
        fontName="Helvetica", fontSize=9,
        textColor=COLOR_ACCENT, leading=14,
        leftIndent=12, spaceAfter=2,
    )
    styles["methodology"] = ParagraphStyle(
        "methodology",
        fontName="Helvetica", fontSize=8.5,
        textColor=COLOR_MUTED, leading=13,
    )
    styles["footer"] = ParagraphStyle(
        "footer",
        fontName="Helvetica-Oblique", fontSize=7.5,
        textColor=COLOR_MUTED, alignment=TA_CENTER,
    )

    return styles
